# Generated by Django 4.0.5 on 2022-06-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_change_email', 'Can change the user email')]},
        ),
    ]
