# Generated by Django 4.0.2 on 2022-04-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
