# Generated by Django 4.0.2 on 2022-03-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_contactus_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email_from',
            field=models.CharField(max_length=100),
        ),
    ]
