# Generated by Django 4.0.2 on 2022-03-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_contactus_email_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='reply_to',
            field=models.EmailField(max_length=100),
        ),
    ]
