# Generated by Django 4.0.2 on 2022-03-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_contactus_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='reply_to',
            field=models.EmailField(max_length=254),
        ),
    ]
